export const initialProjects = [
  {id:'wanderlust', title:'WanderLust', subtitle:'Full-stack accommodation listing platform', description:'Built to understand the complete journey of a web request — from a listing form to an Express route, a MongoDB document, and a rendered page.', highlights:['Listing creation, editing, and deletion','Related listings and reviews with Mongoose','Joi validation and centralized error handling'], tags:['Node.js','Express','MongoDB','EJS'], status:'In development', visibility:'published', github:'https://github.com/adithyadiwanad-sudo/wanderlust-project', demo:'', image:''},
  {id:'neuroshield', title:'NeuroShield IDS', subtitle:'AI-powered network intrusion detection', description:'My final-year project explores how machine learning can help identify network attacks. I’m working toward a connected detection pipeline with a dashboard for reviewing threats.', highlights:['Focused on network intrusion detection','Python model service and Node.js backend','Ongoing model evaluation and dashboard integration'], tags:['Python','scikit-learn','React','Node.js'], status:'In development', visibility:'published', github:'https://github.com/adithyadiwanad-sudo/NeuroShield', demo:'', image:''}
];
export function escapeHTML(value) { return String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
export function renderProjects(projects) {
  return projects.filter(p => p.visibility === 'published').map((p, i) => {
    const e = escapeHTML;
    const image = p.image ? `<img class="project-screenshot" src="${e(p.image)}" alt="${e(p.title)} project screenshot" loading="lazy" width="800" height="500">` : `<div class="visual-heading">${e(p.title)}</div><div class="project-concepts">${p.tags.map(t=>`<span>${e(t)}</span>`).join('')}</div><p class="visual-caption mono">${e(p.subtitle)}</p>`;
    return `<article class="project"><div class="project-visual ${i%2?'security-visual':'web-visual'}"><div class="visual-top"><span class="mono">PROJECT ${String(i+1).padStart(2,'0')}</span><span class="visual-category">${e(p.status)}</span></div>${image}</div><div class="project-body"><div class="project-meta"><span class="mono">SELECTED WORK</span><span class="status ${p.status==='Completed'?'':'in-progress'}">${e(p.status)}</span></div><h3>${e(p.title)}</h3><p class="project-subtitle">${e(p.subtitle)}</p><p class="project-description">${e(p.description)}</p><ul class="project-highlights">${p.highlights.map(t=>`<li>${e(t)}</li>`).join('')}</ul><div class="tags">${p.tags.map(t=>`<span>${e(t)}</span>`).join('')}</div><div class="project-actions">${p.github?`<a href="${e(p.github)}" target="_blank" rel="noopener noreferrer">View code ↗</a>`:''}${p.demo?`<a href="${e(p.demo)}" target="_blank" rel="noopener noreferrer">Live demo ↗</a>`:''}</div></div></article>`;
  }).join('\n') || '<p>No projects are published yet.</p>';
}
